# Generated by Django 4.1.2 on 2022-10-11 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 17, 20, 25, 401537)),
        ),
    ]
